services:
 rabbitmq:
   image: rabbitmq:4.1-management
   container_name: rabbitmq-server
   hostname: rabbitmq
   ports:
     - "5672:5672"
     - "15672:15672"
     - "5552:5552"
   env_file:
     - .env
   environment:
     RABBITMQ_DEFAULT_USER: admin
     RABBITMQ_DEFAULT_PASS: password123
   volumes:
     - rabbitmq_data:/var/lib/rabbitmq
     - rabbitmq_logs:/var/log/rabbitmq
     - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
     - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
   networks:
     - rabbitmq_network
   restart: unless-stopped
   healthcheck:
     test: ["CMD", "rabbitmq-diagnostics", "ping"]
     interval: 30s
     timeout: 10s
     retries: 5

 sender:
   build:
     context: ./sender
     dockerfile: Dockerfile
   env_file:
     - .env
   container_name: sender
   depends_on:
     rabbitmq:
       condition: service_healthy
   networks:
     - rabbitmq_network
   restart: "no"
   volumes:
     - ./commands:/app/commands

 receiver:
   build:
     context: ./receiver
     dockerfile: Dockerfile
   ports:
     - "8501:8501"
   env_file:
     - .env
   container_name: receiver
   depends_on:
     rabbitmq:
       condition: service_healthy
   networks:
     - rabbitmq_network

volumes:
 rabbitmq_data:
   driver: local
 rabbitmq_logs:
   driver: local

networks:
 rabbitmq_network:
   driver: bridge